Issue#130 グラフの範囲変更
susatthi/flutter-apps pull request #234
Opened 2023-10-21 09:32 UTC by sukekyo-net

# 関連する Issue

- close #130

# やったこと

- チャート上部に  グラフの表示範囲を 1週間・1ヶ月・3ヶ月・1年 で切り替えるボタンを追加した
- グラフの表示期間に合わせて、チャートのデータ、タイトルの期間、チャートX軸の期間を変更するようにした
- ダミーデータを デイリーで 1年超(400日)生成する処理を追加した。(以前の処理も残しています。)

# やらないこと

- 切り替えた表示範囲設定をユーザデータとして保存する
- チャートの当日にすぐに移動できるようなボタンの用意
  - あると良いと思いましたが、本件では対応していません

# できていないこと
- 表示範囲の切り替え時に、チャートX軸の表示が一瞬ごちゃつく
  - 1ヶ月・3ヶ月・1年のX軸に表示する日付を間引いているものの、一時的に全て表示するような動作となっている  

# スクリーンショット
ランダムデータだから、という点もあるかもしれませんが、年のチャートが見てもわからない状態なので、
月平均のデータ等にしてもよさそうですね。

![#130](https://github.com/susatthi/flutter-apps/assets/5939882/0256226c-b4e0-44e5-b73d-b6ffb1f1c73c)

2023-10-21 09:34 UTC, sukekyo-net commented
@susatthi 
こちら対応しました。お手隙でご確認お願い致します。
Issueにコメントしていた 下記が解決しておりません。。。
> グラフを切り替えた時にX軸のラベルも切り替えているが、切り替える際に一瞬ごちゃつくため修正したい。

2023-10-21 23:01 UTC, susatthi commented
@sukekyo-net 

ありがとうございます！コードレビューの前に実装内容についてお願いさせてください！コードレビューは実装内容確定後にします！

### 依頼事項

- 今までのダミーデータも使いたいので、デバッグ画面で次のようにしておいてほしいです！
  - ダミーデータへ入れ替え
  - ダミーデータ（ランダム）へ入れ替え
- 表示範囲の切り替え時に、チャートX軸の表示が一瞬ごちゃつく件について
  - 直してコミットしてみたので、参考にして手直しをお願いします！
- 表示範囲切替直後は、常に「今週」「今月」「今年」になるようにしてほしいです。
  - 例えば、1週間→1ヶ月→1週間、と切り替えると、1週間のときに「12月12日〜18日」になってしまいます。これを「今週」にしたいです。
  - 1週間のときに左右フリックで範囲を切り替えたあとに1ヶ月に切り替えたときにリセットされるのは問題なしにしたいです！

2023-11-03 10:48 UTC, sukekyo-net commented
@susatthi 
少々時間空いてしまいましたが、ご依頼事項について対応いたしました。
ご確認お願いいたします！

2023-11-04 22:53 UTC, susatthi requested changes
レビューしました！ご確認、修正お願い致します！

2023-11-04 22:53 UTC, susatthi commented on packages/asthma_diary_app/lib/feature/peak_flow/data/peak_flow.dart
> +  final int months;
weeklyでは使わないし、使用側でも結局 ChartPeriodType  を switch で分岐させているので、`months` は削除しちゃいたいです。

2023-11-04 22:53 UTC, susatthi commented on packages/asthma_diary_app/lib/feature/peak_flow/state/peak_flow_chart_state.dart
> +  }
ChartPeriodTypeに List<DateTimeRange> への変換機能を extension で持たせた方がコードの見通しがよくなると思いますので、やってみてほしいです！

こんな感じです。せっかくなので、dart3で導入された switch 拡張も使ってみました。

```dart
  ・・・

  return periodType.toChartRanges(
    startMeasuredAt,
    endMeasuredAt,
  );
}

extension on ChartPeriodType {
  List<DateTimeRange> toChartRanges(
    DateTime startMeasuredAt,
    DateTime endMeasuredAt,
  ) =>
      switch (this) {
        ChartPeriodType.weekly => _getWeeklyChartRanges(
            startMeasuredAt,
            endMeasuredAt,
          ),
        ChartPeriodType.monthly => _getMonthlyChartRanges(
            startMeasuredAt,
            endMeasuredAt,
          ),
        ChartPeriodType.quarterly => _getQuarterlyChartRanges(
            startMeasuredAt,
            endMeasuredAt,
          ),
        ChartPeriodType.yearly => _getYearlyChartRanges(
            startMeasuredAt,
            endMeasuredAt,
          ),
      };

  ・・・
}
```

2023-11-04 22:53 UTC, susatthi commented on packages/asthma_diary_app/lib/feature/peak_flow/state/peak_flow_chart_state.dart
> +}
コードの見通しがよくなるので DateTimeRange の extension にしたいです！

```dart

    // 現在のRange幅とrangesのRange幅が変わった場合、最大値を返す
    if (currentRange.toChartPeriodType() !=
        chartState.ranges.first.toChartPeriodType()) {
      return chartState.ranges.length - 1;
    }

extension on DateTimeRange {
  /// [DateTimeRange] から [ChartPeriodType] を算出する
  ChartPeriodType toChartPeriodType() {
    final rangeDays = end.difference(start).inDays;

    // 1週間
    if (rangeDays <= 7) {
      return ChartPeriodType.weekly;
    }
    // 1ヶ月
    if (7 < rangeDays && rangeDays < 32) {
      return ChartPeriodType.monthly;
    }
    // 3ヶ月
    if (32 <= rangeDays && rangeDays < 94) {
      return ChartPeriodType.quarterly;
    }
    // 1年
    return ChartPeriodType.yearly;
  }
}
```

2023-11-04 22:53 UTC, susatthi commented on packages/asthma_diary_app/lib/feature/peak_flow/ui/component/peak_flow_chart.dart
> +    );
文字色は foregroundColor が使えます！あと、Whiteではなく primary の反対色 である onPrimary を使うと良い感じです！

```suggestion
    // 選択状態で背景色と文字色を変更
    final textButtonStyle = selected
        ? TextButton.styleFrom(
            backgroundColor: context.primary,
            foregroundColor: context.onPrimary,
          )
        : null;

    return TextButton(
      onPressed: onPressed,
      style: textButtonStyle,
      child: Text(item.displayName),
    );

```

2023-11-04 22:53 UTC, susatthi commented on packages/asthma_diary_app/lib/feature/peak_flow/ui/component/peak_flow_chart.dart
> +      };
extension にしちゃったほうが見通しがよくなると思います！

```dart
extension on ChartPeriodType {
  int get sideTitleWidgetWidthAdjust => switch (this) {
        ChartPeriodType.weekly => 7,
        ChartPeriodType.monthly => 10,
        ChartPeriodType.quarterly => 15,
        ChartPeriodType.yearly => 12,
      };
}
```

2023-11-04 22:53 UTC, susatthi commented on packages/asthma_diary_app/lib/feature/peak_flow/ui/component/peak_flow_chart.dart
> +class __LineChartXTitleLabel extends StatelessWidget {
ここも extension にしちゃった方が良さそうです！

2023-11-05 14:55 UTC, sukekyo-net commented
@susatthi 
レビューありがとうございます。対応いたしました。
extention は自分の中でも使うかどうかの基準がはっきりしていないので、
コメント助かります。

2023-11-05 21:55 UTC, susatthi commented
@sukekyo-net 

マージお願いします！

![LGTM](https://image.lgtmoon.dev/227155)

2023-11-05 21:56 UTC, susatthi approved these changes

2023-11-05 23:54 UTC, merged