チャートの当日に移動できるボタンを追加
susatthi/flutter-apps pull request #245
Opened 2023-11-18 03:22 UTC by sukekyo-net

# 関連する Issue

- close #235

# やったこと

- 期間のセレクタの右に 当日へ移動できるボタンを追加した
- 期間の粒度に応じて、ボタンの文言を変更するようにした
- 表示している期間が、当日を含んでいる場合はボタンが非表示となるようにした

# やらないこと

- なし

# スクリーンショット
<img width="320" alt="#235_android" src="https://github.com/susatthi/flutter-apps/assets/5939882/c6167b7f-06b7-4edf-b0ed-437b01011c44">

2023-11-18 03:26 UTC, sukekyo-net commented
@susatthi 
こちら、対応いたしました。
ご確認お願いいたします。

2023-11-18 21:31 UTC, susatthi requested changes
PRありがとうございます！1点指摘したのでご確認お願い致します！

2023-11-18 21:31 UTC, susatthi commented on packages/asthma_diary_app/lib/feature/peak_flow/ui/component/peak_flow_chart.dart
> +      ),
他のボタンと同化しているので、次のようなアイコンボタンにしてほしいです！

```suggestion
     child: IconButton(
        onPressed: () => _moveToNow(ref),
        icon: const Icon(Icons.today),
      ),
```

2023-11-18 22:55 UTC, sukekyo-net commented
@susatthi 
>他のボタンと同化しているので、次のようなアイコンボタンにしてほしいです！

対応しました！確かにアイコンの方が横幅も取らないので良いですね！
<img width="300" alt="#235_iconbutton" src="https://github.com/susatthi/flutter-apps/assets/5939882/52a69261-45a0-4010-ad00-5d6fa4a0189d">

2023-11-19 08:13 UTC, susatthi commented
マージお願いします！

![LGTM](https://image.lgtmoon.dev/228520)

2023-11-19 11:21 UTC, merged